[tool.poetry]
name = "pyetr-api"
version = "0.1.0"
description = ""
authors = ["Mark Todd <mark@dreamingspires.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<4.0.0"
pyetr = ">=1.0.0,<2.0.0"
fastapi = "^0.115.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pyright]
venvPath="./"
venv=".venv"